application: danugroup
version: 3 
runtime: python27
api_version: 1
threadsafe: true 

libraries:
- name: django
  version: "1.9"
- name: PIL
  version: "1.1.7"
- name: MySQLdb
  version: "1.2.5"
- name: ssl
  version: latest

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

handlers:
- url: /jsjquery
  static_dir: static/jsjquery/

- url: /cssjquery
  static_dir: static/cssjquery/

- url: /csssocial
  static_dir: static/csssocial/

- url: /jssocial
  static_dir: static/jssocial/

- url: /imgdanu
  static_dir: static/imgdanu/

- url: /jsghg
  static_dir: static/jsghg/

- url: /cssghg
  static_dir: static/cssghg/

- url: /imgghg
  static_dir: static/imgghg/

- url: /emissions
  static_dir: static/emissions/

- url: /geo
  static_dir: static/geo/

- url: /static
  static_dir: static

- url: .*
  script: wsgi.application

